Repository wasmerio/wasmer-python, pull requests merged in 2019-05, with the labels that each got.

#25 doc(readme) Fix typos.
  README.md
  tests/test_memory.py
Labels: 📚 documentation, 🧪 tests

#26 chore(dependencies) Update Wasmer to 0.4.0
  Cargo.lock
  Cargo.toml
Labels: 🎉 enhancement, 📦 component-runtime

#27 feat(extension) Implement `__version__` for module
  src/lib.rs
  tests/test_instance.py
Labels: 🎉 enhancement, 📦 component-extension

#30 chore(just) Rename `rust` to `build`
  .circleci/config.yml
  README.md
  justfile
Labels: 🎉 enhancement, 🤖 bot

#34 chore(runtime) Update Wasmer to 0.4.1
  Cargo.lock
  Cargo.toml
Labels: 📦 component-runtime

#35 chore(bors) Setup Bors
  .circleci/config.yml
  bors.toml
Labels: 🤖 bot

#36 Add documentation to instance.rs
  src/instance.rs
Labels: 🎉 enhancement, 📚 documentation

#42 chore(runtime) Update Wasmer to 0.4.2
  Cargo.lock
  Cargo.toml
Labels: 🎉 enhancement, 📦 component-runtime

#43 doc(examples) Add the `greet` example
  examples/greet.py
  examples/greet.rs
  examples/greet.wasm
Labels: 🎉 enhancement, 📚 documentation
