Repository wasmerio/wasmer-python, pull requests merged in 2020-11, with the labels that each got.

#412 chore: Update dependencies
  Cargo.lock
  packages/api/Cargo.toml
  packages/compiler-cranelift/Cargo.toml
  packages/compiler-llvm/Cargo.toml
  packages/compiler-singlepass/Cargo.toml
  packages/engines/Cargo.toml
Labels: dependencies, 🎉 enhancement

#418 fix(readme): Change logo URL
  packages/api/README.md
Labels: 🐞 bug, 📚 documentation

#416 feat(compiler-llvm) Re-enable `wasmer_compiler_llvm` with new prebuilds
  .github/workflows/test.yml
  Cargo.lock
  docs/api/engine/index.html
  docs/api/target/index.html
  docs/api/wasi/index.html
  docs/api/wasmer/index.html
  docs/api/wasmer_compiler_cranelift/index.html
  docs/api/wasmer_compiler_llvm/index.html
  docs/api/wasmer_compiler_singlepass/index.html
  justfile
  packages/any/setup.py
  packages/api/Cargo.toml
  packages/compiler-cranelift/Cargo.toml
  packages/compiler-llvm/Cargo.toml
  packages/compiler-singlepass/Cargo.toml
  packages/engines/Cargo.toml
  tests/test_store.py
Labels: 🎉 enhancement, 📚 documentation, 📦 component-extension, 🧪 tests

#420 feat(api) Avoid using a closure to declare host function
  Cargo.lock
  packages/api/src/externals/function.rs
Labels: 🎉 enhancement, 📦 component-extension
