Repository wasmerio/wasmer-python, pull requests merged in 2020-03, with the labels that each got.

#132 feat(runtime) Update Wasmer to 0.14
  Cargo.lock
  Cargo.toml
Labels: 🎉 enhancement, 📦 component-runtime

#135 test(ci) Test against Python 3.8.2 rather than 3.8.0
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: 🎉 enhancement, 🤖 bot, 🧪 tests

#136 Fixed spelling of dictionaries
  README.md
Labels: 🐞 bug, 📚 documentation

#139 feat(runtime) Update Wasmer to 0.15
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: 🎉 enhancement, 📦 component-runtime

#141 test(ci) Use `actions/setup-python` to speed up CI
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: 🎉 enhancement, 🤖 bot, 🧪 tests

#143 fix(github-actions) Fix the `release` script since version numbers have changed
  .github/workflows/release.yml
Labels: 🐞 bug, 🤖 bot

#146 feat(instance) Introduce `Instance.call_function_by_index`
  Cargo.lock
  Cargo.toml
  src/instance/exports.rs
  src/instance/mod.rs
  src/module.rs
  tests/test_instance.py
Labels: 🎉 enhancement, 📦 component-extension, 📦 component-runtime, 🧪 tests

#147 feat(instance) Replace `call_function_by_index` by `resolve_exported_function`
  src/instance/mod.rs
  tests/test_instance.py
Labels: 🎉 enhancement, 📦 component-extension

#148 feat(instance) `ExportedFunction.getfullargspec` returns a `FullArgSpec` named tuple
  src/instance/exports.rs
  src/instance/inspect.rs
  src/lib.rs
  src/module.rs
  src/type.rs
  tests/test_instance.py
  tests/test_type.py
Labels: 🎉 enhancement, 📦 component-extension, 🧪 tests

#153 feat(extension) Update to Pyo3 0.9
  Cargo.lock
  Cargo.toml
  src/instance/exports.rs
  src/instance/globals.rs
  src/instance/mod.rs
  src/memory/buffer.rs
  src/module.rs
  src/value.rs
Labels: 🎉 enhancement, 📦 component-extension
